# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-04 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0002_exportsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportfile',
            name='filename',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='File name'),
        ),
    ]
