# This file is part of Booktype.
# Copyright (c) 2012 Aleksandar Erkalovic <aleksandar.erkalovic@sourcefabric.org>
#
# Booktype is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Booktype is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Booktype.  If not, see <http://www.gnu.org/licenses/>.

import os

PUBLISH_OPTIONS =  ['book', 'ebook', 'lulu', 'pdf', 'odt']

OBJAVI_URL =  "http://objavi.booki.cc/objavi.cgi"

THIS_BOOKI_SERVER = os.environ.get('HTTP_HOST', 'booktype-demo.sourcefabric.org')

CREATE_BOOK_VISIBLE = True
CREATE_BOOK_LICENSE = ""

FREE_REGISTRATION = True
ADMIN_CREATE_BOOKS = False
ADMIN_IMPORT_BOOKS = False

# These are default options for CSS settings

BOOKTYPE_CSS_BOOK = '.objavi-chapter{ \n  color: #000; \n} \n\na { \n  text-decoration:none; \n  color:#000; \n} \n\nh1 .initial{ \n  color: #000; \n} \n\n.objavi-subsection{ \n  display: block; \n  page-break-before: always; \n/* page-break-after: always;*/ \n  text-transform: uppercase; \n  font-size: 20pt; \n} \n\nbody .objavi-subsection:first-child{ \n  page-break-before: avoid; \n} \n\n\n.objavi-subsection .initial { \n  font-size: 1em; \n  color: #000; \n} \n\n.objavi-subsection-heading { \n  font-size: 20pt; \n  text-align: center; \n  line-height: 300px; \n  font-weight: normal; \n} \n\n\nh1 { \n  page-break-before: always; \n} \n\n\ntable { \n  float: none; \n} \n\nh1.frontpage{ \n  page-break-after:always; \n  margin-top:70%; \n  font-size: 20pt; \n  text-align: center; \n  page-break-before: avoid; \n  font-weight: normal; \n} \n\ndiv.copyright{ \n  padding: 1em; \n} \n/* TOC ******************************/ \ntable { \n  float: none; \n} \n\ntable.toc { \n  font-size: 1.1em; \n  width: 95%; \n} \n\ntable.toc td{ \n  vertical-align:top \n  padding-left: 0.5em; \n} \n\ntd.chapter { \n  padding: 0 0.5em; \n  text-align: right; \n} \n\ntable.toc td.pagenumber { \n  text-align: right; \n  vertical-align:bottom; \n} \n\ntd.section { \n  padding-top: 1.1em; \n  font-weight: bold; \n} \n/* End TOC **************************/ \n\n\npre { \n  overflow: hidden; \n  white-space: pre-wrap; \n} \n\n\nh1, h2, h3, h4, h5, h6{ \n  page-break-after: avoid; \n  page-break-inside: avoid; \n} \n\n\n.page-break{ \n  page-break-before: always; \n  height: 7em; \n  display: block; \n} \n\n\n#right-footer { \n  text-align: right; \n} \n\n#left-footer { \n  text-align: left; \n} \n\na { \n  word-wrap: break-word; \n} \n\n.objavi-no-page-break { \n  page-break-inside: avoid; \n} \n\n.unseen{ \n  z-index: -66; \n  margin-left: -1000pt; \n}\nsup {\n  vertical-align:text-top;\n  font-size:0.7em; \n} \n\t '

BOOKTYPE_CSS_EBOOK = '.objavi-chapter{\n  color: #000;\n  display:none;\n} \n\na {\n  text-decoration:none;\n  color:#000;\n} \n\nh1 .initial{\n  color: #000;\n  display:none;\n} \n\n.objavi-subsection{\n  display: block;\n  page-break-before: always;\n} \n\nbody .objavi-subsection:first-child{\n  page-break-before: avoid;\n} \n\n.objavi-subsection .initial {\n  color: #000;\n  display:none;\n} \n\n.objavi-subsection-heading {\n  font-size: 20pt;\n  text-align: center;\n  line-height: 300px;\n  font-weight: normal;\n} \n\ntable {\n  float: none;\n} \n\nh1.frontpage{\n  page-break-after:always;\n  margin-top:70%;\n  font-size: 20pt;\n  text-align: center;\n  page-break-before: avoid;\n  max-width: 700pt;\n  font-weight: normal;\n} \n\ndiv.copyright{\n  padding: 1em;\n}\n/* TOC ******************************/\ntable {\n  float: none;\n} \n\ntable.toc {\n  font-size: 1.1em;\n  width: 95%;\n} \n\ntable.toc td {\n  vertical-align:top\n  padding-left: 0.5em;\n} \n\ntd.chapter {\n  padding: 0 0.5em;\n  text-align: right;\n} \n\ntable.toc td.pagenumber {\n  text-align: right;\n  vertical-align:bottom;\n} \n\ntd.section {\n  padding-top: 1.1em;\n  font-weight: bold;\n}\n\t\t\t\t\t\n/* End TOC **************************/ \nimg {\n   max-width: 500px;\n   height: auto;\n} \n\n.objavi-no-page-break {\n   page-break-inside: avoid;\n} \n\n.unseen {\n   z-index: -66;\n   margin-left: -1000pt;\n} \n\n.objavi-subsection-heading{\n  height:860px;\n  font-size:0px;\n  display:block;\n}\n'

BOOKTYPE_CSS_LULU = '.objavi-chapter{\n\t    color: #000;\n\t    display:none;\n\t    } \n\n\t    a {\n\t    text-decoration:none;\n\t    color:#000;\n\t    } \n\n\t    h1 .initial{\n\t    color: #000;\n\t    display:none;\n\t    } \n\n\n\t    .objavi-subsection{\n\t    display: block;\n\t    page-break-before: always;\n\t    } \n\n\t    body .objavi-subsection:first-child{\n\t    page-break-before: avoid;\n\t    } \n\n\t    .objavi-subsection .initial {\n\t    color: #000;\n\t    display:none;\n\t    } \n\n\t    .objavi-subsection-heading {\n\t    font-size: 20pt;\n\t    text-align: center;\n\t    line-height: 300px;\n\t    font-weight: normal;\n\t    } \n\n\t    table {\n\t    float: none;\n\t    } \n\n\t    h1.frontpage{\n\t    page-break-after:always;\n\t    margin-top:70%;\n\t    font-size: 20pt;\n\t    text-align: center;\n\t    page-break-before: avoid;\n\t    max-width: 700pt;\n\t    font-weight: normal;\n\t    } \n\n\t    div.copyright{\n\t    padding: 1em;\n\t    }\n\t    /* TOC ******************************/\n\t    table {\n\t    float: none;\n\t    } \n\n\t    table.toc {\n\t    font-size: 1.1em;\n\t    width: 95%;\n\t    } \n\n\t    table.toc td{\n\t    vertical-align:top\n\t    padding-left: 0.5em;\n\t    } \n\n\t    td.chapter {\n\t    padding: 0 0.5em;\n\t    text-align: right;\n\t    } \n\n\t    table.toc td.pagenumber {\n\t    text-align: right;\n\t    vertical-align:bottom;\n\t    } \n\n\t    td.section {\n\t    padding-top: 1.1em;\n\t    font-weight: bold;\n\t    }\n\t    /* End TOC **************************/ \n\n\t    img {\n\t    max-width: 500px;\n\t    height: auto;\n\t    } \n\n\t    .objavi-no-page-break {\n\t    page-break-inside: avoid;\n\t    } \n\n\t    .unseen{\n\t    z-index: -66;\n\t    margin-left: -1000pt;\n\t    } \n\n\n\t    .objavi-subsection-heading{\n\t    height:860px;\n\t    font-size:0px;\n\t    display:block;\n\t    }\n \nsup {\n  vertical-align:text-top;\n  font-size:0.7em; \n} \n\t '

BOOKTYPE_CSS_PDF = '.objavi-subsection{ \n  display: block; \n  page-break-before: always; \n/* page-break-after: always;*/ \n  text-transform: uppercase; \n  font-size: 20pt; \n} \n\nbody .objavi-subsection:first-child{ \n  page-break-before: avoid; \n} \n\n\n.objavi-subsection .initial { \n  font-size: 1em; \n  color: #000; \n} \n\n.objavi-subsection-heading { \n  font-size: 20pt; \n  text-align: center; \n  line-height: 300px; \n  font-weight: normal; \n} \n\n\nh1 { \n  page-break-before: always; \n} \n\n\ntable { \n  float: none; \n} \n\nh1.frontpage{ \n  page-break-after:always; \n  margin-top:70%; \n  font-size: 20pt; \n  text-align: center; \n  page-break-before: avoid; \n  font-weight: normal; \n} \n\ndiv.copyright{ \n  padding: 1em; \n} \n/* TOC ******************************/ \ntable { \n  float: none; \n} \n\ntable.toc { \n  font-size: 1.1em; \n  width: 95%; \n} \n\ntable.toc td{ \n  vertical-align:top \n  padding-left: 0.5em; \n} \n\ntd.chapter { \n  padding: 0 0.5em; \n  text-align: right; \n} \n\ntable.toc td.pagenumber { \n  text-align: right; \n  vertical-align:bottom; \n} \n\ntd.section { \n  padding-top: 1.1em; \n  font-weight: bold; \n} \n/* End TOC **************************/ \n\n\n\npre { \n  overflow: hidden; \n  white-space: pre-wrap; \n} \n\n\nh1, h2, h3, h4, h5, h6{ \n  page-break-after: avoid; \n  page-break-inside: avoid; \n} \n\n\n.page-break{ \n  page-break-before: always; \n  height: 7em; \n  display: block; \n} \n\na { \n  word-wrap: break-word; \n} \n\n.objavi-no-page-break { \n  page-break-inside: avoid; \n} \n\n/*To force a blank page it is sometimes necessary to add unseen \n content. Display:none and visibility: hidden do not work -- the \n renderer realises that they are not there and skips the page. So we \n add a tiny bit of text beyond the margin of the page. \n*/ \n.unseen{ \n  z-index: -66; \n  margin-left: -1000pt; \n}'

BOOKTYPE_CSS_ODT = 'body {\n}\n\n#book-title {\n    font-size: 64pt;\n    page-break-before: avoid;\n    margin-bottom: 12em;  \n    max-width: 700px;\n}\n\n.unseen {\n    display: none;\n}\n\n.chapter {\n    color: #000;\n}\n\nh1 .initial {\n    color: #000;\n    font-size: 2em;\n}\n\nbody .subsection:first-child {\n}\n\nh1 {\n  page-break-before: always;\n}\n\n.objavi-subsection{\n   text-transform: uppercase;\n   font-size: 20pt;\n}\n\n.objavi-subsection .initial {\n   font-size: 1em;\n   color: #000;\n}\n\n.objavi-subsection-heading{\n   font-size: 36pt;\n   font-weight: bold;\n   page-break-before: always;\n}\n\ntable {\n   float: none;\n}\n\nh1.frontpage{\n   font-size: 64pt;\n   text-align: center;\n   max-width: 700px;\n}\n\ndiv.copyright{\n    padding: 1em;\n}\n\npre {\n   max-width:700px;\n   overflow: hidden;\n}\n\nimg {\n   max-width: 700px;\n   height: auto;\n}\n'
