tinyMCE.addI18n('en.bookiimage_dlg',{
    'dialog_title': 'Insert Image',
    'general': 'General',
    'appearance': 'Appearance',
    'image_url': 'Image URL',
    'browse': 'Browse',
    'title': 'Title',
    'preview': 'Preview',
    'align': 'Align',
    'not_set': '-- Not Set --',
    'baseline': 'Baseline',
    'top': 'Top',
    'middle': 'Middle',
    'bottom': 'Bottom',
    'text_top': 'Text Top',
    'text_bottom': 'Text Bottom',
    'left': 'Left',
    'right': 'Right',
    'dimensions': 'Dimensions',
    'width': 'Width',
    'constrain': 'Constrain Proportions',
    'vertical': 'Vertical Space',
    'horizontal': 'Horizontal Space',
    'border': 'Border',
    'css_id': 'CSS ID',
    'css_class': 'CSS class',
    'upload': 'Upload',
    'images': 'Images',
    'upload_image': 'Upload image',
    'name': 'name',
    'dimension': 'dimension',
    'size': 'size',
    'date': 'date'
});
