tinyMCE.addI18n('es.bookiimage_dlg',{
    'dialog_title': 'Insertar imagen',
    'general': 'General',
    'appearance': 'Apariencia',
    'image_url': 'URL de la imagen',
    'browse': 'Navegar',
    'title': 'Título',
    'preview': 'Previsualizar',
    'align': 'Alinear',
    'not_set': '-- No establecido --',
    'baseline': 'Línea base',
    'top': 'Superior',
    'middle': 'Medio',
    'bottom': 'Inferior',
    'text_top': 'Texto superior',
    'text_bottom': 'Texto inferior',
    'left': 'Izquierda',
    'right': 'Derecha',
    'dimensions': 'Dimensiones',
    'width': 'Ancho',
    'constrain': 'Limitar proporciones',
    'vertical': 'Espacio vertical',
    'horizontal': 'Espacio horizontal',
    'border': 'Borde',
    'css_id': 'ID de CSS',
    'css_class': 'clase de CSS',
    'upload': 'Cargar',
    'images': 'Imágenes',
    'upload_image': 'Cargar imagen',
    'name': 'nombre',
    'dimension': 'dimensión',
    'size': 'tamaño',
    'date': 'fecha'
});
