tinyMCE.addI18n('fr.bookiimage_dlg',{
    'dialog_title': 'Ins\u00e9rer une image',
    'general': 'G\u00e9n\u00e9ral',
    'appearance': 'Apparence',
    'image_url': 'URL de l\'image',
    'browse': 'S\u00e9lectionner',
    'title': 'Titre',
    'preview': 'Pr\u00e9visualisation',
    'align': 'Alignement',
    'not_set': '-- Non d\u00e9fini --',
    'baseline': 'Ligne de base',
    'top': 'Haut',
    'middle': 'Milieu',
    'bottom': 'Bas',
    'text_top': 'Haut du texte',
    'text_bottom': 'Bas du texte',
    'left': 'Gauche',
    'right': 'Droite',
    'dimensions': 'Dimensions',
    'width': 'Largeur',
    'constrain': 'Contraindre les proportions',
    'vertical': 'Espacement vertical',
    'horizontal': 'Espaceme horizontal',
    'border': 'Contours',
    'css_id': 'Identifiant CSS',
    'css_class': 'Classe CSS',
    'upload': 'T\u00e9l\u00e9verser',
    'images': 'Images',
    'upload_image': 'T\u00e9l\u00e9verser l\'image',
    'name': 'nom',
    'dimension': 'dimension',
    'size': 'taille',
    'date': 'date',
    'insert': 'Ins\u00e9rer',
    'cancel': 'Annuler'
});
