tinyMCE.addI18n('it.bookiimage_dlg',{
    'dialog_title': 'Inserisci immagine',
    'general': 'Generale',
    'appearance': 'Aspetto',
    'image_url': 'URL Immagine',
    'browse': 'Sfoglia',
    'title': 'Titolo',
    'preview': 'Anteprima',
    'align': 'Allineamento',
    'not_set': '-- Not Set --',
    'baseline': 'Standard',
    'top': 'Alto',
    'middle': 'Centale',
    'bottom': 'Basso',
    'text_top': 'Testo in Alto',
    'text_bottom': 'Testo in basso',
    'left': 'Sinistra',
    'right': 'Destra',
    'dimensions': 'Dimensioni',
    'width': 'Larghezza',
    'constrain': 'Forza Proporzioni',
    'vertical': 'Spazio verticale',
    'horizontal': 'Spazio orizzontale',
    'border': 'Bordo',
    'css_id': 'CSS ID',
    'css_class': 'CSS class',
    'upload': 'Carica',
    'images': 'Immagini',
    'upload_image': 'Carica immagine',
    'name': 'nome',
    'dimension': 'dimensione',
    'size': 'peso',
    'date': 'data'
});
