tinyMCE.addI18n('ru.bookiimage_dlg',{
    'dialog_title': 'Вставить изображение',
    'general': 'Общее',
    'appearance': 'Внешний вид',
    'image_url': 'URL изображения',
    'browse': 'Искать',
    'title': 'Заголовок',
    'preview': 'Предпросмотр',
    'align': 'Выровнять',
    'not_set': '-- Не установлено --',
    'baseline': 'Базовая линия',
    'top': 'Верхняя часть',
    'middle': 'Середина',
    'bottom': 'Нижняя часть',
    'text_top': 'Верхняя часть текста',
    'text_bottom': 'Нижняя часть текста',
    'left': 'Лево',
    'right': 'Право',
    'dimensions': 'Измерения',
    'width': 'Ширина',
    'constrain': 'Сохранять пропорции',
    'vertical': 'Вертикальное пространство',
    'horizontal': 'Горизонтальное пространство',
    'border': 'Граница',
    'css_id': 'CSS ID',
    'css_class': 'Класс CSS',
    'upload': 'Загрузить',
    'images': 'Изображения',
    'upload_image': 'Загрузить изображение',
    'name': 'название',
    'dimension': 'измерение',
    'size': 'размер',
    'date': 'дата'
});
