# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-01 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0007_booktoc_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookstatus',
            name='color',
            field=models.CharField(blank=True, default=b'', max_length=30, verbose_name='color'),
        ),
    ]
