# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-28 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0008_bookstatus_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='content_json',
            field=models.TextField(blank=True, null=True, verbose_name='content json'),
        ),
    ]
