# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-09-08 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0009_chapter_content_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcover',
            name='booksize',
            field=models.CharField(blank=True, default=b'', max_length=30, verbose_name='Booksize'),
        ),
        migrations.AlterField(
            model_name='bookcover',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='bookcover',
            name='height',
            field=models.IntegerField(blank=True, default=0, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='bookcover',
            name='unit',
            field=models.CharField(blank=True, default=b'px', max_length=20, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='bookcover',
            name='width',
            field=models.IntegerField(blank=True, default=0, verbose_name='Width'),
        ),
    ]
