# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-08 22:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0012_chapter_assigned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='assigned',
        ),
    ]
