# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-08 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0013_remove_chapter_assigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='assigned',
            field=models.CharField(blank=True, default=b'', max_length=100, verbose_name='assigned'),
        ),
    ]
