# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-01-29 15:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0012_auto_20171227_2303'),
        ('editor', '0014_chapter_assigned'),
    ]

    operations = [
    ]
