# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-27 13:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0009_chapter_content_json'),
        ('themes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.CharField(max_length=32)),
                ('custom', models.TextField(default=b'{}')),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='editor.Book')),
            ],
        ),
    ]
