# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-27 14:15
from __future__ import unicode_literals

from django.db import migrations

from booktype.utils.misc import get_available_themes


def migrate_themes_data(apps, schema_editor):
    Book = apps.get_model("editor", "Book")
    UserTheme = apps.get_model("themes", "UserTheme")
    BookTheme = apps.get_model("themes", "BookTheme")

    available_themes = get_available_themes()

    for book in Book.objects.all():
        for user_theme in UserTheme.objects.filter(book=book, owner=book.owner):
            theme = BookTheme()
            theme.book = book
            theme.custom = user_theme.custom
            theme.active = available_themes[0]

            if user_theme.active in available_themes:
                theme.active = user_theme.active

            theme.save()


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0002_theme'),
    ]

    operations = [
        migrations.RunPython(migrate_themes_data),
    ]
