#!/bin/bash
#postinst script for Booktype

set -e

if [ "$DPKG_DEBUG" = "developer" ]; then
    set -x
fi

case "$1" in
  configure|reconfigure)
  ;;

  abort-upgrade|abort-remove|abort-deconfigure)
  ;;

  *)
       echo "postinst called with unknown argument \`$1'" >&2
       exit 1
  ;;
esac

#DEBHELPER#

exit 0
