#!/bin/bash
#preinst script for Booktype

set -e

if [ "$DPKG_DEBUG" = "developer" ]; then
    set -x
fi

case "$1" in
  install|upgrade)

  ;;

  abort-upgrade)
    echo "Upgrade aborting..." >&2
  ;;

  *)
       echo "preinst called with unknown argument \`$1'" >&2
       exit 1
  ;;
esac

#DEBHELPER#

exit 0
