#!/bin/bash
#prerm script for Booktype

set -e

case "$1" in
  remove|purge)
  ;;

  upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
  ;;

  *)
      echo "prerm called with unknown argument \`$1'" >&2
      exit 1
  ;;
esac

#DEBHELPER#

exit 0
