# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-19 23:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edit', '0002_invitecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitecode',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_codes', to='editor.Book'),
        ),
        migrations.AlterField(
            model_name='invitecode',
            name='code',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
    ]
