# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-08 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edit', '0004_auto_20170816_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='edit.ChatThread'),
        ),
    ]
